ToCode Solution: תרגול Shell Glob
tocodeil/unix1-course-examples pull request #104
Opened 2017-05-20 12:44 UTC by Yulia88

2017-05-21 05:27 UTC, ynonp requested changes
Hi Yulia,

Great work all in all. I loved your searching around for solutions even outside lesson materials (eg. using find).

I suggested some improvements and you still have one answer that doesn't work and needs fixing.

2017-05-21 05:27 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +Why test.c as well?
The problem is with the forward slash `/`:

Your glob pattern matches all the files in all directories which (the directory) start with an uppercase letter.

Better to skip the second part of the glob and leave it at:

```
ls -d [[:upper:]]*
```

Or, if you also want to see the contents of each directory drop the d:

```
ls [[:upper:]]*
```

Alternatively, showing all the FILES that start with an uppercase in all directories would look like this:

```
ls -d */[[:upper:]]*
```

2017-05-21 05:27 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +echo *[a,e,i,o,u]
Better without the comma: `*[aeiou]`. A comma is a character like any other and so a file named `hi,` will match your pattern

2017-05-21 05:27 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +ls *.c src/
That doesn't work. It shows .c files from current directory AND all files in src directory. You can try and create a `main.c` file in the current directory and a `demo.h` file in src to see the problem

2017-05-21 05:27 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +find -name '*.c'
That works. But you can also solve it using glob patterns. Do give it a second thought

2017-05-21 05:27 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +find -name '*.png* -delete
Again- works, but I'd rather see a solution using glob patterns

2017-05-21 05:27 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +
I gave some hints there. Let me know if it helped.

2017-05-21 05:27 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +ls -d D*
👍

2017-05-21 16:32 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +Why test.c as well?
Can you please explain why

>  Or, if you also want to see the contents of each directory drop the d:
> 
> ls [[:upper:]]*
shows me the following? why also the lower case file
![glob](https://cloud.githubusercontent.com/assets/28634107/26285619/2beca708-3e5c-11e7-93bd-4bf0a7c0a991.JPG)

2017-05-21 16:37 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +echo *[a,e,i,o,u]
I have the same output for both, I don't understand the difference, can you please explain?

2017-05-21 16:57 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +ls *.c src/
the only way I succeed is by actually being inside the src dir
![capture](https://cloud.githubusercontent.com/assets/28634107/26285804/a7658302-3e5f-11e7-9aa1-f816107cf21a.JPG)

2017-05-21 17:31 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +
Was printed everything within the upper case folders which is Doc/ 
But how do I show only files with upper case in only Doc

2017-05-21 17:35 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +find -name '*.c'
Finally!!
ls -d */*[.c]

2017-05-21 17:42 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +find -name '*.c'
👍 
(though you can do just fine without the square brackets - `ls -d */*.c`)

2017-05-21 17:44 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +find -name '*.png* -delete
rm -d */*[.png]

2017-05-21 17:45 UTC, Yulia88 reviewed
I have added fixes

2017-05-21 17:45 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +echo *[a,e,i,o,u]
Try this:

```
touch xyz, xa
echo *[aeiou]
echo *[a,e,i,o,u]
```

On my machine this is the output:

```
# for echo *[aeiou]:
file xa

# for echo *[a,e,i,o,u]
file xa xyz,
```

Different outputs when a file ends in a comma

2017-05-21 17:47 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +echo *[a,e,i,o,u]
Got it, so basically the comma as you explained is a character and it will find such files if they exist

2017-05-21 17:49 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +find -name '*.png* -delete
I assume you mean - `rm */*.png`

1. No `-d` for rm
2. Square brackets around a word is never a good idea

2017-05-21 17:59 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +
Not sure I understand - what command are you running and what output do you expect to see?

2017-05-21 18:08 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +find -name '*.c'
Re. your question - please also attach the output of `tree` so we can see which files you actually have in that folder

2017-05-21 18:34 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +find -name '*.png* -delete
Yes, i can't print "*" in here for some reason 
1. ok
2. ok

2017-05-21 18:51 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +find -name '*.c'
Still have an issue with installing the tree
I have responded in the "tree" question

2017-05-21 18:53 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +
I meant that I understood the answer ( I think) 
the command ls -l [A-Z]* prints out everything within the upper case folder which is Doc

What I asked was how do I print out upper case files only in Doc folder only

2017-05-23 07:22 UTC, closed without merging

2017-05-23 17:08 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +find -name '*.c'
Attached snapshot 
![tree](https://cloud.githubusercontent.com/assets/28634107/26366381/8d3db996-3ff3-11e7-9d82-ae6457071b5c.JPG)

2017-05-23 17:12 UTC, Yulia88 commented on 12_glob_lab/globlab.txt
> +find -name '*.c'
Here is the snapshot
In overall I have 4 png files 
ls command shows only 3 png although there are 4 
![tree](https://cloud.githubusercontent.com/assets/28634107/26366526/1b31f028-3ff4-11e7-8431-5baaab54ac00.JPG)

2017-05-23 17:41 UTC, ynonp commented on 12_glob_lab/globlab.txt
> +find -name '*.c'
Command should be `ls */*.png` (we'll talk about the reasons tomorrow if it's still not clear)