ToCode Solution: תרגול: מבוא לשורת הפקודה
tocodeil/unix1-course-examples pull request #109
Opened 2017-05-25 14:19 UTC by Nadav1234

2017-05-27 17:10 UTC, ynonp requested changes
Please add a working solution for the last question

2017-05-27 17:10 UTC, ynonp commented on 07_cmd_lab/cmdlab.txt
> +
👍

2017-05-27 17:10 UTC, ynonp commented on 07_cmd_lab/cmdlab.txt
> +
Well it does contain user data, but no password is stored there for a few decades :) You can find the actual encrypted passwords in `/etc/shadow`

2017-05-27 17:10 UTC, ynonp commented on 07_cmd_lab/cmdlab.txt
> +ls -s /etc
That should be `ls -S /etc`. To actually see it working though you'll want to add -l, so try: `ls -lS /etc`

2017-05-27 17:10 UTC, ynonp commented on 07_cmd_lab/cmdlab.txt
> +date -R
Didn't work on my machine. Can you paste the output `date -R` printed? It should be formatted as `Sun 23/03/2010 14:30` (i.e. first a day, then the date dd/mm/yyyy and then the time HH:MM)

2017-05-28 13:11 UTC, Nadav1234 commented
>  4. Print current date/time formatted as: "Sun 21/03/2010, 14:30". Hint:
read "man date" and search for the correct format string.
+
+date -R
Didn't work on my machine. Can you paste the output date -R printed? It
should be formatted as Sun 23/03/2010 14:30 (i.e. first a day, then the
date dd/mm/yyyy and then the time HH:MM)

$date +"%A %d/%m/%Y %R"
Not quite sure if there's supposed to be a shorter option..

On Sat, May 27, 2017 at 8:10 PM, ynonp <notifications@github.com> wrote:

> *@ynonp* requested changes on this pull request.
>
> Please add a working solution for the last question
> ------------------------------
>
> In 07_cmd_lab/cmdlab.txt
> <https://github.com/tocodeil/unix1-course-examples/pull/109#discussion_r118824793>
> :
>
> >    - your default shell?
>    - a list of all shells currently installed on the machine?
>
> +
> +-echo $0
> +-echo $SHELL
> +-cat /etc/shells
> +
>
> 👍
> ------------------------------
>
> In 07_cmd_lab/cmdlab.txt
> <https://github.com/tocodeil/unix1-course-examples/pull/109#discussion_r118824806>
> :
>
> >  עברית שפה קשה. בעקרון המעטפת הנוכחית שלי היא bash
>
>  2. View the file /etc/passwd on your machine with the command "cat /etc/passwd". Then read about the file in "man 5 passwd". What information is held in the file? What are the fields in each line?
>
> +-Contains all users passwords in the following format:
> +login name:optional encrypted password:numerical user ID:numerical group ID:user name or comment field:user home directory:optional user command interpreter
> +
>
> Well it does contain user data, but no password is stored there for a few
> decades :) You can find the actual encrypted passwords in /etc/shadow
> ------------------------------
>
> In 07_cmd_lab/cmdlab.txt
> <https://github.com/tocodeil/unix1-course-examples/pull/109#discussion_r118824817>
> :
>
> >  3. In Unix, the /etc folder holds configuration files. Display all files in "/etc" folder ordered by file size (Hint: search in "man ls")
>
> +ls -s /etc
>
> That should be ls -S /etc. To actually see it working though you'll want
> to add -l, so try: ls -lS /etc
> ------------------------------
>
> In 07_cmd_lab/cmdlab.txt
> <https://github.com/tocodeil/unix1-course-examples/pull/109#discussion_r118824832>
> :
>
> >  4. Print current date/time formatted as: "Sun 21/03/2010, 14:30". Hint: read "man date" and search for the correct format string.
> +
> +date -R
>
> Didn't work on my machine. Can you paste the output date -R printed? It
> should be formatted as Sun 23/03/2010 14:30 (i.e. first a day, then the
> date dd/mm/yyyy and then the time HH:MM)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tocodeil/unix1-course-examples/pull/109#pullrequestreview-40656905>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AbnKdGQjru8su0E2RSGNxEc4kPt9QPkrks5r-Fj0gaJpZM4NmcGY>
> .
>

2017-05-29 09:35 UTC, ynonp commented
This one worked well.

2017-05-29 09:35 UTC, closed without merging